name: SefaceServerSelector
description: A Minecraft Java Edition plugin to connect between servers via GUI.
main: net.sefaceblocks.SefaceServerSelector
version: 1.1.0
commands:
  servers:
    description: Switch servers through a GUI.
    usage: /<command>
    permission: seface.command.servers
    aliases:
      - sv
