name: seface-server-selector
description: A Minecraft Java Edition plugin to connect between servers via GUI.
main: net.sefaceblocks.SefaceServerSelector
version: 1.0.0
api-version: 1.18
commands:
  servers:
    description: Switch servers through a GUI.
    usage: /<command>
    aliases:
      - sv
