name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🔃
        uses: actions/checkout@v2

      - name: Installing JDK 16 ☕
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven dependencies 📦
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Building with Maven 🔨
        run: mvn -B package --file pom.xml
